baseURL = "https://www.jasonbennett.name/"
languageCode = "en-us"
title = "jasonbennett.name"
theme = "solar-theme-hugo"
paginate = 5
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256
copyright = ""

[params]
  scheme = "dark" # light, dark, gray or preference
  description = "it's hip to be rhombus"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/index.html"
  [[menu.main]]
    name = "Essays"
    url = "https://github.com/bake/solar-theme-hugo/"
  [[menu.main]]
    name = "Projects"
    url = "https://themes.gohugo.io/solar-theme-hugo/"
  [[menu.main]]
    name = "About"
    url = "https://themes.gohugo.io/solar-theme-hugo/"
  [[menu.other]]
    name = "Other Stuff"
    url = "https://themes.gohugo.io/solar-theme-hugo/"

